export interface ProductDetail {
  name: string
  slug: string
  variety: string
  description: string
  features: string[]
  season: string
  duration: string
  specs: Record<string, string>
}

export interface CategoryDetail {
  name: string
  description: string
  longDescription: string
  image: string
  products: ProductDetail[]
}

function generateSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")
}

export const allProductData: Record<string, CategoryDetail> = {
  "hybrid-maize": {
    name: "Hybrid Maize",
    description: "High-yielding hybrid maize varieties for Kharif & Rabi seasons with wider adaptability.",
    longDescription: "Our hybrid maize seeds are developed through extensive research to deliver maximum yield in Indian agro-climatic conditions. Vasudha Agri Seeds maize hybrids are known for their wider adaptability, biotic stress tolerance, and excellent grain quality suitable for both Kharif and Rabi seasons.",
    image: "/images/slide-harvest.jpg",
    products: [
      {
        name: "GURU-4062",
        slug: generateSlug("GURU-4062"),
        variety: "Hybrid Maize",
        description: "High yield potential maize hybrid with wider adaptability. Tall plants 250-260cm with orange semi flint grains. Excellent biotic stress tolerance.",
        features: ["High Yield", "Wider Adaptability", "Biotic Stress Tolerant"],
        season: "Kharif & Rabi",
        duration: "Kharif 110-115, Rabi 115-120 days",
        specs: {
          "Crop Duration": "Kharif - 110 - 115 Days, Rabi - 115 - 120 Days",
          "Plant Height": "Tall Plants - 250 - 260 cm",
          "Stick & Foliage": "Medium Semi Erect, erect & green foliage",
          "Cob Shape & Shank": "Conico cylindrical cobs, Thin white shank with compact grain filling, cob placement medium to high",
          "Grain Colour & Texture": "Orange Semi flint grains",
          "Specific Features": "High Yield Potential, Wider adaptability, Erect canopy and tolerant to biotic stresses",
          "Cultivation Period": "Suitable for Both Kharif and Rabi Season",
        },
      },
      {
        name: "ASKAR-111",
        slug: generateSlug("ASKAR-111"),
        variety: "Hybrid Maize",
        description: "Tall plants 254-264cm with orange yellow semi flint grains. Suitable for high density planting with erect canopy and compact grain filling.",
        features: ["High Density Planting", "Erect Canopy", "Compact Filling"],
        season: "Kharif & Rabi",
        duration: "Kharif 110-115, Rabi 115-120 days",
        specs: {
          "Crop Duration": "Kharif - 110 - 115 Days, Rabi - 115 - 120 Days",
          "Plant Height": "Tall Plants - 254 - 264 cm",
          "Stick & Foliage": "Medium Semi Erect, erect & green foliage",
          "Cob Shape & Shank": "Conico cylindrical cobs, Thin white shank with compact grain filling, cob placement medium to high",
          "Grain Colour & Texture": "Orange Yellow Semi flint grains",
          "Specific Features": "High Density Planting, Erect canopy, compact grain filling with wider adaptability",
          "Cultivation Period": "Suitable for Both Kharif and Rabi Season",
        },
      },
      {
        name: "CHAMPION-555",
        slug: generateSlug("CHAMPION-555"),
        variety: "Hybrid Maize",
        description: "Conico cylindrical cobs with compact grain filling. Tall plants 252-268cm with medium to dark orange semi dent grains and erect canopy.",
        features: ["Erect Canopy", "Compact Filling", "Wide Adaptability"],
        season: "Kharif & Rabi",
        duration: "Kharif 110-115, Rabi 120-125 days",
        specs: {
          "Crop Duration": "Kharif - 110 - 115 Days, Rabi - 120 - 125 Days",
          "Plant Height": "Tall Plants - 252 - 268 cm",
          "Stick & Foliage": "Medium Semi Erect, erect & green foliage",
          "Cob Shape & Shank": "Conico cylindrical cobs, Thin white shank with compact grain filling, cob placement medium to high",
          "Grain Colour & Texture": "Medium to Dark Orange Semi dent grains",
          "Specific Features": "Erect canopy, compact grain filling, wide adaptability and tolerant to biotic stresses",
          "Cultivation Period": "Suitable for Both Kharif and Rabi Season",
        },
      },
      {
        name: "ARJUN-111",
        slug: generateSlug("ARJUN-111"),
        variety: "Hybrid Maize",
        description: "Medium tall plants 220-230cm with medium to dark orange semi flint grains. High yield potential with excellent erect canopy structure.",
        features: ["High Yield", "Erect Canopy", "Biotic Stress Tolerant"],
        season: "Kharif & Rabi",
        duration: "Kharif 110-120, Rabi 120-125 days",
        specs: {
          "Crop Duration": "Kharif - 110 - 120 Days, Rabi - 120 - 125 Days",
          "Plant Height": "Medium Tall Plants - 220 - 230 cm",
          "Stick & Foliage": "Medium Semi Erect, erect & green foliage, predominantly purple colour silks",
          "Cob Shape & Shank": "Conico cylindrical cobs, Thin white shank with compact grain filling, cob placement medium to high",
          "Grain Colour & Texture": "Medium to Dark Orange light Yellow Semi flint grains",
          "Specific Features": "High Yield Potential, Wider adaptability, Erect canopy and tolerant to biotic stresses",
          "Cultivation Period": "Suitable for Both Kharif and Rabi Season",
        },
      },
      {
        name: "VIRAT-777",
        slug: generateSlug("VIRAT-777"),
        variety: "Hybrid Maize",
        description: "Tall plants 250-260cm with orange semi flint grains. Excellent moisture stress tolerance with stay green character. Suitable for cattle feed.",
        features: ["Moisture Stress Tolerant", "Stay Green", "Cattle Feed Suitable"],
        season: "Kharif & Rabi",
        duration: "Kharif 110-115, Rabi 115-120 days",
        specs: {
          "Crop Duration": "Kharif - 110 - 115 Days, Rabi - 115 - 120 Days",
          "Plant Height": "Tall Plants - 250 - 260 cm",
          "Stick & Foliage": "Medium Semi Erect, erect & green foliage",
          "Cob Shape & Shank": "Conico cylindrical cobs, Thin white shank with compact grain filling, cob placement medium to high",
          "Grain Colour & Texture": "Orange Semi flint grains",
          "Specific Features": "Moisture stress tolerant, stay green character, suitable for cattle feed purpose",
          "Cultivation Period": "Suitable for Both Kharif and Rabi Season",
        },
      },
      {
        name: "CHATRAPATHI-555",
        slug: generateSlug("CHATRAPATHI-555"),
        variety: "Hybrid Maize",
        description: "Tall plants 250-260cm with orange yellow semi flint grains. Suitable for high density planting with compact grain filling and wide adaptability.",
        features: ["High Density Planting", "Compact Filling", "Wide Adaptability"],
        season: "Kharif & Rabi",
        duration: "Kharif 110-115, Rabi 115-120 days",
        specs: {
          "Crop Duration": "Kharif - 110 - 115 Days, Rabi - 115 - 120 Days",
          "Plant Height": "Tall Plants - 250 - 260 cm",
          "Stick & Foliage": "Medium Semi Erect, erect & green foliage",
          "Cob Shape & Shank": "Conico cylindrical cobs, Thin white shank with compact grain filling, cob placement medium to high",
          "Grain Colour & Texture": "Orange Yellow Semi flint grains",
          "Specific Features": "High Density Planting, compact grain filling with wider adaptability",
          "Cultivation Period": "Suitable for Both Kharif and Rabi Season",
        },
      },
      {
        name: "POWER-4055",
        slug: generateSlug("POWER-4055"),
        variety: "Hybrid Maize",
        description: "Tall plants 250-260cm with medium to dark orange semi dent grains. High yield potential with erect canopy and biotic stress tolerance.",
        features: ["High Yield", "Erect Canopy", "Biotic Stress Tolerant"],
        season: "Kharif & Rabi",
        duration: "Kharif 110-115, Rabi 120-125 days",
        specs: {
          "Crop Duration": "Kharif - 110 - 115 Days, Rabi - 120 - 125 Days",
          "Plant Height": "Tall Plants - 250 - 260 cm",
          "Stick & Foliage": "Medium Semi Erect, erect & green foliage",
          "Cob Shape & Shank": "Conico cylindrical cobs, Thin white shank with compact grain filling, cob placement medium to high",
          "Grain Colour & Texture": "Medium to Dark Orange Semi dent grains",
          "Specific Features": "High Yield Potential, Erect canopy and tolerant to biotic stresses",
          "Cultivation Period": "Suitable for Both Kharif and Rabi Season",
        },
      },
      {
        name: "BIG BOSS-009",
        slug: generateSlug("BIG BOSS-009"),
        variety: "Hybrid Maize",
        description: "Medium tall plants 220-230cm with wide adaptability. Erect canopy structure with excellent biotic stress tolerance for diverse conditions.",
        features: ["Wide Adaptability", "Erect Canopy", "Biotic Stress Tolerant"],
        season: "Kharif & Rabi",
        duration: "Kharif 110-120, Rabi 120-125 days",
        specs: {
          "Crop Duration": "Kharif - 110 - 120 Days, Rabi - 120 - 125 Days",
          "Plant Height": "Medium Tall Plants - 220 - 230 cm",
          "Stick & Foliage": "Medium Semi Erect, erect & green foliage",
          "Cob Shape & Shank": "Conico cylindrical cobs, Thin white shank with compact grain filling, cob placement medium to high",
          "Grain Colour & Texture": "Orange Semi flint grains",
          "Specific Features": "Wide Adaptability, Erect canopy and tolerant to biotic stresses",
          "Cultivation Period": "Suitable for Both Kharif and Rabi Season",
        },
      },
      {
        name: "BUNNY-999",
        slug: generateSlug("BUNNY-999"),
        variety: "Hybrid Maize",
        description: "Tall plants 250-260cm with orange semi flint grains. Moisture stress tolerant with stay green character. Suitable for cattle feed purpose.",
        features: ["Moisture Stress Tolerant", "Stay Green", "Cattle Feed"],
        season: "Kharif & Rabi",
        duration: "Kharif 110-115, Rabi 115-120 days",
        specs: {
          "Crop Duration": "Kharif - 110 - 115 Days, Rabi - 115 - 120 Days",
          "Plant Height": "Tall Plants - 250 - 260 cm",
          "Stick & Foliage": "Medium Semi Erect, erect & green foliage, stay green character",
          "Cob Shape & Shank": "Conico cylindrical cobs, Thin white shank with compact grain filling",
          "Grain Colour & Texture": "Orange Semi flint grains",
          "Specific Features": "Moisture stress tolerant, stay green character, suitable for cattle feed",
          "Cultivation Period": "Suitable for Both Kharif and Rabi Season",
        },
      },
      {
        name: "GARUDA-666",
        slug: generateSlug("GARUDA-666"),
        variety: "Hybrid Maize",
        description: "Tall plants 250-260cm with orange yellow semi flint grains. Suitable for high density planting with erect canopy and wide adaptability.",
        features: ["High Density Planting", "Erect Canopy", "Wide Adaptability"],
        season: "Kharif & Rabi",
        duration: "Kharif 110-115, Rabi 115-120 days",
        specs: {
          "Crop Duration": "Kharif - 110 - 115 Days, Rabi - 115 - 120 Days",
          "Plant Height": "Tall Plants - 250 - 260 cm",
          "Stick & Foliage": "Medium Semi Erect, erect & green foliage",
          "Cob Shape & Shank": "Conico cylindrical cobs, Thin white shank with compact grain filling",
          "Grain Colour & Texture": "Orange Yellow Semi flint grains",
          "Specific Features": "High Density Planting, Erect canopy with wider adaptability",
          "Cultivation Period": "Suitable for Both Kharif and Rabi Season",
        },
      },
      {
        name: "ADITYA-369",
        slug: generateSlug("ADITYA-369"),
        variety: "Hybrid Maize",
        description: "Tall plants 250-260cm with high yield potential. Erect canopy structure with excellent biotic stress tolerance for both seasons.",
        features: ["High Yield", "Erect Canopy", "Biotic Stress Tolerant"],
        season: "Kharif & Rabi",
        duration: "Kharif 110-115, Rabi 120-125 days",
        specs: {
          "Crop Duration": "Kharif - 110 - 115 Days, Rabi - 120 - 125 Days",
          "Plant Height": "Tall Plants - 250 - 260 cm",
          "Stick & Foliage": "Medium Semi Erect, erect & green foliage",
          "Cob Shape & Shank": "Conico cylindrical cobs, Thin white shank with compact grain filling, cob placement medium to high",
          "Grain Colour & Texture": "Orange Semi flint grains",
          "Specific Features": "High Yield Potential, Erect canopy and tolerant to biotic stresses",
          "Cultivation Period": "Suitable for Both Kharif and Rabi Season",
        },
      },
      {
        name: "RUDHRA-888",
        slug: generateSlug("RUDHRA-888"),
        variety: "Hybrid Maize",
        description: "Tall plants 250-260cm with orange semi flint grains. Moisture stress tolerant with stay green character. Excellent for cattle feed.",
        features: ["Moisture Stress Tolerant", "Stay Green", "Cattle Feed"],
        season: "Kharif & Rabi",
        duration: "Kharif 110-115, Rabi 115-120 days",
        specs: {
          "Crop Duration": "Kharif - 110 - 115 Days, Rabi - 115 - 120 Days",
          "Plant Height": "Tall Plants - 250 - 260 cm",
          "Stick & Foliage": "Medium Semi Erect, erect & green foliage, stay green character",
          "Cob Shape & Shank": "Conico cylindrical cobs, Thin white shank with compact grain filling",
          "Grain Colour & Texture": "Orange Semi flint grains",
          "Specific Features": "Moisture stress tolerant, stay green character, excellent for cattle feed",
          "Cultivation Period": "Suitable for Both Kharif and Rabi Season",
        },
      },
    ],
  },
  "hybrid-paddy": {
    name: "Hybrid Paddy",
    description: "Premium hybrid paddy seeds with high yield and disease tolerance.",
    longDescription: "Vasudha Agri Seeds hybrid paddy varieties are developed for high yield potential, disease tolerance, and excellent grain quality. Our paddy hybrids are suitable for diverse soil and climatic conditions across India.",
    image: "/images/seeds-variety.jpg",
    products: [
      {
        name: "KAVERI-111",
        slug: generateSlug("KAVERI-111"),
        variety: "Long Bold Slender Paddy",
        description: "120-125 days duration with long bold slender grains. Medium plant height 100-110cm with 380-400 grains per panicle. Tolerant to Blast & BPH. Suitable for boiled rice.",
        features: ["High Yield", "Blast Tolerant", "Long Slender"],
        season: "Kharif",
        duration: "120-125 days",
        specs: {
          "Crop Duration": "120 - 125 Days",
          "Plant Height": "Medium - 100 - 110 cm",
          "Grain Type": "Long Bold Slender",
          "Grains per Panicle": "380 - 400",
          "Disease Tolerance": "Tolerant to Blast & BPH",
          "Specific Features": "High yield potential, suitable for boiled rice preparation",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
      {
        name: "AISHWARYA-444",
        slug: generateSlug("AISHWARYA-444"),
        variety: "Medium Bold Paddy",
        description: "128-130 days duration with medium bold grains. Medium plant height 110-120cm with 380-400 grains per panicle. Tolerant to BLB disease.",
        features: ["High Yield", "BLB Tolerant", "Medium Bold"],
        season: "Kharif",
        duration: "128-130 days",
        specs: {
          "Crop Duration": "128 - 130 Days",
          "Plant Height": "Medium - 110 - 120 cm",
          "Grain Type": "Medium Bold",
          "Grains per Panicle": "380 - 400",
          "Disease Tolerance": "Tolerant to BLB disease",
          "Specific Features": "High yield potential with good grain quality",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
      {
        name: "GANGOTHRI-333",
        slug: generateSlug("GANGOTHRI-333"),
        variety: "Short Bold Paddy",
        description: "140-145 days duration with short bold grains. Medium plant height 120-125cm with 380-400 grains per panicle. Suitable for boiled rice preparation.",
        features: ["Short Bold", "Blast Tolerant", "Boiled Rice"],
        season: "Kharif",
        duration: "140-145 days",
        specs: {
          "Crop Duration": "140 - 145 Days",
          "Plant Height": "Medium - 120 - 125 cm",
          "Grain Type": "Short Bold",
          "Grains per Panicle": "380 - 400",
          "Disease Tolerance": "Tolerant to Blast",
          "Specific Features": "Suitable for boiled rice preparation, high yield",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
      {
        name: "AARADHYA-555",
        slug: generateSlug("AARADHYA-555"),
        variety: "Long Bold Paddy",
        description: "130-135 days duration with long bold grains. Medium plant height 125-130cm with 380-400 grains per panicle. High yield with blast tolerance.",
        features: ["High Yield", "Long Bold", "Blast Tolerant"],
        season: "Kharif",
        duration: "130-135 days",
        specs: {
          "Crop Duration": "130 - 135 Days",
          "Plant Height": "Medium - 125 - 130 cm",
          "Grain Type": "Long Bold",
          "Grains per Panicle": "380 - 400",
          "Disease Tolerance": "Tolerant to Blast",
          "Specific Features": "High yield potential with long bold grain quality",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
      {
        name: "GODAVARI-666",
        slug: generateSlug("GODAVARI-666"),
        variety: "Long Slender Paddy",
        description: "130-135 days duration with long slender grains. Medium plant height 120-125cm with 400-420 grains per panicle. Strong tillers suitable for all soils.",
        features: ["All Soils", "Strong Tillers", "High Yield"],
        season: "Kharif",
        duration: "130-135 days",
        specs: {
          "Crop Duration": "130 - 135 Days",
          "Plant Height": "Medium - 120 - 125 cm",
          "Grain Type": "Long Slender",
          "Grains per Panicle": "400 - 420",
          "Disease Tolerance": "Good overall disease tolerance",
          "Specific Features": "Strong tillers, high yield potential with long slender grains",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
      {
        name: "ISHA-777",
        slug: generateSlug("ISHA-777"),
        variety: "Long Bold Slender Paddy",
        description: "100-110 days duration with long bold slender grains. Medium plant height 120-125cm with 400-420 grains per panicle. Early maturity variety.",
        features: ["Early Maturity", "All Soils", "High Yield"],
        season: "Kharif",
        duration: "100-110 days",
        specs: {
          "Crop Duration": "100 - 110 Days",
          "Plant Height": "Medium - 120 - 125 cm",
          "Grain Type": "Long Bold Slender",
          "Grains per Panicle": "400 - 420",
          "Disease Tolerance": "Good overall disease tolerance",
          "Specific Features": "Early maturity variety with high yield potential",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
    ],
  },
  "research-paddy": {
    name: "Research Paddy",
    description: "Improved paddy varieties with superior grain quality and adaptability.",
    longDescription: "Our research paddy varieties are developed through dedicated breeding programs at Vasudha Agri Biotech. These improved varieties offer superior grain quality, disease tolerance, and adaptability to diverse growing conditions.",
    image: "/images/farmer-field.jpg",
    products: [
      {
        name: "MAHA LAKSHMI-2233",
        slug: generateSlug("MAHA LAKSHMI-2233"),
        variety: "Long Slender Paddy",
        description: "130-135 days duration with long slender grains. Medium plant height 100-110cm with 230-250 grains per panicle. Tolerant to blast and suitable for all soils.",
        features: ["Long Slender", "All Soils", "Blast Tolerant"],
        season: "Kharif",
        duration: "130-135 days",
        specs: {
          "Crop Duration": "130 - 135 Days",
          "Plant Height": "Medium - 100 - 110 cm",
          "Grain Type": "Long Slender",
          "Grains per Panicle": "230 - 250",
          "Disease Tolerance": "Tolerant to Blast",
          "Specific Features": "Long slender grains with good cooking quality",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
      {
        name: "BHARATHI-777",
        slug: generateSlug("BHARATHI-777"),
        variety: "Long Slender Paddy",
        description: "120-125 days duration with long slender grains. Medium plant height 110-120cm with 350-400 grains per panicle. High yield potential for all soils.",
        features: ["High Yield", "All Soils", "Long Slender"],
        season: "Kharif",
        duration: "120-125 days",
        specs: {
          "Crop Duration": "120 - 125 Days",
          "Plant Height": "Medium - 110 - 120 cm",
          "Grain Type": "Long Slender",
          "Grains per Panicle": "350 - 400",
          "Disease Tolerance": "Good overall disease tolerance",
          "Specific Features": "High yield potential with long slender grain quality",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
      {
        name: "VAISHNAVI-111",
        slug: generateSlug("VAISHNAVI-111"),
        variety: "Long Slender Paddy",
        description: "120-125 days duration with long slender grains. Short plant height 85-90cm with 340-400 grains per panicle. Blast tolerant for all soils.",
        features: ["Short Plant", "All Soils", "Blast Tolerant"],
        season: "Kharif",
        duration: "120-125 days",
        specs: {
          "Crop Duration": "120 - 125 Days",
          "Plant Height": "Short - 85 - 90 cm",
          "Grain Type": "Long Slender",
          "Grains per Panicle": "340 - 400",
          "Disease Tolerance": "Tolerant to Blast",
          "Specific Features": "Short plant height with high yield, blast tolerant",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
      {
        name: "LEPAKSHI-555",
        slug: generateSlug("LEPAKSHI-555"),
        variety: "Short Bold Paddy",
        description: "145-150 days duration with short bold grains. Medium plant height 120-125cm with 275-320 grains per panicle. Long duration variety for all soils.",
        features: ["Short Bold", "Long Duration", "All Soils"],
        season: "Kharif",
        duration: "145-150 days",
        specs: {
          "Crop Duration": "145 - 150 Days",
          "Plant Height": "Medium - 120 - 125 cm",
          "Grain Type": "Short Bold",
          "Grains per Panicle": "275 - 320",
          "Disease Tolerance": "Good overall disease tolerance",
          "Specific Features": "Long duration variety with short bold grains",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
      {
        name: "SARASWATHI-888",
        slug: generateSlug("SARASWATHI-888"),
        variety: "Short Bold Paddy",
        description: "130-135 days duration with short bold grains. Medium plant height 125-130cm with 275-320 grains per panicle. High yield for all soils.",
        features: ["Short Bold", "All Soils", "High Yield"],
        season: "Kharif",
        duration: "130-135 days",
        specs: {
          "Crop Duration": "130 - 135 Days",
          "Plant Height": "Medium - 125 - 130 cm",
          "Grain Type": "Short Bold",
          "Grains per Panicle": "275 - 320",
          "Disease Tolerance": "Good overall disease tolerance",
          "Specific Features": "High yield potential with short bold grains",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
      {
        name: "VIJAY-222",
        slug: generateSlug("VIJAY-222"),
        variety: "Long Slender Paddy",
        description: "115-120 days duration with long slender grains. Short plant height 85-90cm with 220-230 grains per panicle. Early maturity variety.",
        features: ["Early Maturity", "Long Slender", "All Soils"],
        season: "Kharif",
        duration: "115-120 days",
        specs: {
          "Crop Duration": "115 - 120 Days",
          "Plant Height": "Short - 85 - 90 cm",
          "Grain Type": "Long Slender",
          "Grains per Panicle": "220 - 230",
          "Disease Tolerance": "Good overall disease tolerance",
          "Specific Features": "Early maturity variety with long slender grains",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
      {
        name: "SRI KRISHNA-1122",
        slug: generateSlug("SRI KRISHNA-1122"),
        variety: "Medium Slender Paddy",
        description: "130-135 days duration with medium slender grains. Medium plant height 95-100cm with 350-370 grains per panicle. Blast tolerant for all soils.",
        features: ["Medium Slender", "All Soils", "Blast Tolerant"],
        season: "Kharif",
        duration: "130-135 days",
        specs: {
          "Crop Duration": "130 - 135 Days",
          "Plant Height": "Medium - 95 - 100 cm",
          "Grain Type": "Medium Slender",
          "Grains per Panicle": "350 - 370",
          "Disease Tolerance": "Tolerant to Blast",
          "Specific Features": "Medium slender grains with blast tolerance",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
      {
        name: "VASUDHA-555",
        slug: generateSlug("VASUDHA-555"),
        variety: "Super Fine Paddy",
        description: "130-135 days duration with super fine grains. Medium plant height 95-100cm with 400-450 grains per panicle. High yield potential for all soils.",
        features: ["Super Fine", "High Yield", "All Soils"],
        season: "Kharif & Rabi",
        duration: "130-135 days",
        specs: {
          "Crop Duration": "130 - 135 Days",
          "Plant Height": "Medium - 95 - 100 cm",
          "Grain Type": "Super Fine",
          "Grains per Panicle": "400 - 450",
          "Disease Tolerance": "Good overall disease tolerance",
          "Specific Features": "Super fine grains, high yield potential, suitable for both Kharif & Rabi",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
      {
        name: "SWATHI-444",
        slug: generateSlug("SWATHI-444"),
        variety: "Medium Long Bold Paddy",
        description: "115-120 days duration with medium long bold grains. Medium plant height 125-130cm with 320-360 grains per panicle. Early maturity with blast tolerance.",
        features: ["Early Maturity", "All Soils", "Blast Tolerant"],
        season: "Kharif",
        duration: "115-120 days",
        specs: {
          "Crop Duration": "115 - 120 Days",
          "Plant Height": "Medium - 125 - 130 cm",
          "Grain Type": "Medium Long Bold",
          "Grains per Panicle": "320 - 360",
          "Disease Tolerance": "Tolerant to Blast",
          "Specific Features": "Early maturity variety with medium long bold grains",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
      {
        name: "DHRUVA-333",
        slug: generateSlug("DHRUVA-333"),
        variety: "Medium Bold Paddy",
        description: "140-145 days duration with medium bold grains. Medium plant height 125-130cm with 275-320 grains per panicle. High yield for all soils.",
        features: ["Medium Bold", "All Soils", "High Yield"],
        season: "Kharif",
        duration: "140-145 days",
        specs: {
          "Crop Duration": "140 - 145 Days",
          "Plant Height": "Medium - 125 - 130 cm",
          "Grain Type": "Medium Bold",
          "Grains per Panicle": "275 - 320",
          "Disease Tolerance": "Good overall disease tolerance",
          "Specific Features": "High yield potential with medium bold grains",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
    ],
  },
  vegetables: {
    name: "Vegetables",
    description: "Hybrid chilli, tomato, bhendi and bottle gourd seeds for commercial farming.",
    longDescription: "Vasudha Agri Seeds offers a wide range of hybrid vegetable seeds including chilli, tomato, bhendi (okra), and bottle gourd varieties. Our vegetable seeds are developed for high yield, disease resistance, and excellent market quality.",
    image: "/images/slide-vegetables.jpg",
    products: [
      {
        name: "VIJETHA-222 (Chilli)",
        slug: generateSlug("VIJETHA-222 Chilli"),
        variety: "Hybrid Chilli",
        description: "Semi erect plant with 9-11cm smooth dark green to dark red fruits. High pungency, dual purpose hybrid with good colour retention. Suitable for export quality.",
        features: ["High Pungency", "Dual Purpose", "Export Quality"],
        season: "Kharif/Rabi",
        duration: "65-75 days to first picking",
        specs: {
          "Plant Type": "Semi erect, medium to tall plant",
          "Fruit Size": "9 - 11 cm long",
          "Fruit Colour": "Smooth dark green to dark red at maturity",
          "Pungency": "High pungency",
          "Specific Features": "Dual purpose hybrid - suitable for fresh green and dry red. Good colour retention, export quality",
          "Harvesting": "65 - 75 days to first picking",
          "Suitable Season": "Kharif & Rabi",
        },
      },
      {
        name: "KARTHIKEYA-111 (Chilli)",
        slug: generateSlug("KARTHIKEYA-111 Chilli"),
        variety: "Hybrid Chilli",
        description: "12-14cm long fruits with medium pungency. Fresh green chilli variety with good keeping quality and high yield potential.",
        features: ["Fresh Green", "Good Keeping", "High Yield"],
        season: "Kharif/Rabi",
        duration: "65-75 days to first picking",
        specs: {
          "Plant Type": "Semi erect, medium to tall plant",
          "Fruit Size": "12 - 14 cm long",
          "Fruit Colour": "Dark green to red at maturity",
          "Pungency": "Medium pungency",
          "Specific Features": "Fresh green chilli variety, good keeping quality, high yield potential",
          "Harvesting": "65 - 75 days to first picking",
          "Suitable Season": "Kharif & Rabi",
        },
      },
      {
        name: "MUKUNDA-555 (Chilli)",
        slug: generateSlug("MUKUNDA-555 Chilli"),
        variety: "Hybrid Chilli",
        description: "8-10cm fruits with heat set capability. Fresh green chilli variety with good keeping quality for commercial cultivation.",
        features: ["Heat Set", "Fresh Green", "Good Keeping"],
        season: "Kharif/Rabi",
        duration: "60-70 days to first picking",
        specs: {
          "Plant Type": "Semi erect, medium plant",
          "Fruit Size": "8 - 10 cm long",
          "Fruit Colour": "Dark green to red at maturity",
          "Pungency": "Medium pungency",
          "Specific Features": "Heat set capability, fresh green chilli variety, good keeping quality",
          "Harvesting": "60 - 70 days to first picking",
          "Suitable Season": "Kharif & Rabi",
        },
      },
      {
        name: "MEERA-222 (Chilli)",
        slug: generateSlug("MEERA-222 Chilli"),
        variety: "Hybrid Chilli",
        description: "7-9cm fruits with high pungency. Suitable for both fresh and dry purpose with excellent colour retention and good keeping quality.",
        features: ["Fresh & Dry", "High Pungency", "Good Keeping"],
        season: "Kharif/Rabi",
        duration: "65-70 days to first picking",
        specs: {
          "Plant Type": "Semi erect, medium plant",
          "Fruit Size": "7 - 9 cm long",
          "Fruit Colour": "Dark green to dark red at maturity",
          "Pungency": "High pungency",
          "Specific Features": "Suitable for both fresh and dry purpose, excellent colour retention",
          "Harvesting": "65 - 70 days to first picking",
          "Suitable Season": "Kharif & Rabi",
        },
      },
      {
        name: "SARKAR-777 (Tomato)",
        slug: generateSlug("SARKAR-777 Tomato"),
        variety: "Hybrid Tomato",
        description: "Semi determinate, flat round type fruits weighing 80-100g. Very firm with good keeping quality, suitable for long distance transport. Heat tolerant.",
        features: ["Heat Tolerant", "Very Firm", "Long Transport"],
        season: "Rabi/Summer",
        duration: "70-75 days to first harvest",
        specs: {
          "Plant Type": "Semi determinate, vigorous plant",
          "Fruit Shape": "Flat round type",
          "Fruit Weight": "80 - 100 g",
          "Fruit Colour": "Deep red at maturity",
          "Specific Features": "Very firm fruit, good keeping quality, suitable for long distance transport, heat tolerant",
          "Harvesting": "70 - 75 days to first harvest",
          "Suitable Season": "Rabi & Summer",
        },
      },
      {
        name: "DHONI-555 (Tomato)",
        slug: generateSlug("DHONI-555 Tomato"),
        variety: "Hybrid Tomato",
        description: "Square round type fruits weighing 90-100g. Very firm with good keeping quality and high yield potential. Heat tolerant variety.",
        features: ["Heat Tolerant", "Very Firm", "High Yield"],
        season: "Rabi/Summer",
        duration: "70-75 days to first harvest",
        specs: {
          "Plant Type": "Semi determinate, vigorous plant",
          "Fruit Shape": "Square round type",
          "Fruit Weight": "90 - 100 g",
          "Fruit Colour": "Deep red at maturity",
          "Specific Features": "Very firm fruit, good keeping quality, high yield potential, heat tolerant",
          "Harvesting": "70 - 75 days to first harvest",
          "Suitable Season": "Rabi & Summer",
        },
      },
      {
        name: "PAVANI-888 (Bhendi)",
        slug: generateSlug("PAVANI-888 Bhendi"),
        variety: "Hybrid Bhendi",
        description: "Medium to tall plant with 12-14cm dark green pods. Resistance to YVMV and ELCV. High yielding with long shelf life for market.",
        features: ["YVMV Resistant", "High Yield", "Long Shelf Life"],
        season: "Kharif/Summer",
        duration: "45-48 days to first harvest",
        specs: {
          "Plant Type": "Medium to tall, erect plant",
          "Pod Size": "12 - 14 cm long",
          "Pod Colour": "Dark green",
          "Disease Resistance": "Resistance to YVMV and ELCV",
          "Specific Features": "High yielding, long shelf life, suitable for commercial market",
          "Harvesting": "45 - 48 days to first harvest",
          "Suitable Season": "Kharif & Summer",
        },
      },
      {
        name: "TEJA-666 (Bhendi)",
        slug: generateSlug("TEJA-666 Bhendi"),
        variety: "Hybrid Bhendi",
        description: "12-14cm dark green pods with short internodal distance. Resistance to YVMV. High yielding variety with excellent market quality.",
        features: ["YVMV Resistant", "High Yield", "Short Internodal"],
        season: "Kharif/Summer",
        duration: "45-48 days to first harvest",
        specs: {
          "Plant Type": "Medium to tall, erect plant with short internodal distance",
          "Pod Size": "12 - 14 cm long",
          "Pod Colour": "Dark green",
          "Disease Resistance": "Resistance to YVMV",
          "Specific Features": "Short internodal distance, high yielding, excellent market quality",
          "Harvesting": "45 - 48 days to first harvest",
          "Suitable Season": "Kharif & Summer",
        },
      },
      {
        name: "BHAVANI-888 (Bottle Gourd)",
        slug: generateSlug("BHAVANI-888 Bottle Gourd"),
        variety: "Bottle Gourd",
        description: "Long cylindrical fruits 30-40cm weighing 800g-1kg. Early harvest variety with excellent yield potential for commercial cultivation.",
        features: ["Long Cylindrical", "High Weight", "Early Harvest"],
        season: "Kharif/Summer",
        duration: "45-50 days to first harvest",
        specs: {
          "Plant Type": "Vigorous vine with good branching",
          "Fruit Shape": "Long cylindrical",
          "Fruit Size": "30 - 40 cm long",
          "Fruit Weight": "800 g - 1 kg",
          "Specific Features": "Early harvest variety, excellent yield potential for commercial cultivation",
          "Harvesting": "45 - 50 days to first harvest",
          "Suitable Season": "Kharif & Summer",
        },
      },
      {
        name: "SHASHI-666 (Bottle Gourd)",
        slug: generateSlug("SHASHI-666 Bottle Gourd"),
        variety: "Bottle Gourd",
        description: "Bulb shaped fruits weighing 900g-1kg. Powdery mildew tolerant variety with excellent weight and market quality.",
        features: ["Powdery Mildew Tolerant", "Bulb Shape", "High Weight"],
        season: "Kharif/Summer",
        duration: "45-50 days to first harvest",
        specs: {
          "Plant Type": "Vigorous vine with good branching",
          "Fruit Shape": "Bulb shaped",
          "Fruit Weight": "900 g - 1 kg",
          "Disease Tolerance": "Powdery mildew tolerant",
          "Specific Features": "Bulb shaped fruits, excellent weight and market quality",
          "Harvesting": "45 - 50 days to first harvest",
          "Suitable Season": "Kharif & Summer",
        },
      },
    ],
  },
  pulses: {
    name: "Pulses",
    description: "Red gram and pulse varieties for sustainable farming.",
    longDescription: "Vasudha Agri Seeds offers high-quality red gram (pigeon pea) varieties developed for medium maturity, cluster pod formation, and bold seed quality. Our pulse varieties are suitable for diverse growing conditions across India.",
    image: "/images/hero-seeds.jpg",
    products: [
      {
        name: "GANAPATHI-111",
        slug: generateSlug("GANAPATHI-111"),
        variety: "Red Gram",
        description: "Medium maturity red gram variety (140-150 days). Medium tall plants 150-160cm. Pods in clusters of 4-6 per cluster with 3-5 seeds per pod. Medium bold ovoid shaped seeds.",
        features: ["Cluster Pods", "Medium Maturity", "Bold Seeds"],
        season: "Kharif",
        duration: "140-150 days",
        specs: {
          "Crop Duration": "140 - 150 Days (Medium Maturity)",
          "Plant Height": "Medium Tall - 150 - 160 cm",
          "Pod Formation": "Pods in clusters of 4 - 6 per cluster",
          "Seeds per Pod": "3 - 5 seeds per pod",
          "Seed Type": "Medium bold ovoid shaped seeds",
          "Specific Features": "Cluster pod formation, medium maturity, bold seed quality",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
      {
        name: "SHIVAJI-444",
        slug: generateSlug("SHIVAJI-444"),
        variety: "Red Gram",
        description: "Medium maturity red gram variety (140-150 days). Medium tall plants 150-160cm. Pods in clusters of 4-6 per cluster with 3-5 seeds per pod. Medium bold ovoid shaped seeds.",
        features: ["Cluster Pods", "Medium Maturity", "Bold Seeds"],
        season: "Kharif",
        duration: "140-150 days",
        specs: {
          "Crop Duration": "140 - 150 Days (Medium Maturity)",
          "Plant Height": "Medium Tall - 150 - 160 cm",
          "Pod Formation": "Pods in clusters of 4 - 6 per cluster",
          "Seeds per Pod": "3 - 5 seeds per pod",
          "Seed Type": "Medium bold ovoid shaped seeds",
          "Specific Features": "Cluster pod formation, medium maturity, bold seed quality",
          "Suitable Soils": "Suitable for all types of soils",
        },
      },
    ],
  },
}

export function getProductBySlug(category: string, productSlug: string): { product: ProductDetail; categoryData: CategoryDetail } | null {
  const catData = allProductData[category]
  if (!catData) return null

  const product = catData.products.find((p) => p.slug === productSlug)
  if (!product) return null

  return { product, categoryData: catData }
}

export function getAllProductSlugs(): Array<{ category: string; product: string }> {
  const slugs: Array<{ category: string; product: string }> = []
  for (const [category, data] of Object.entries(allProductData)) {
    for (const product of data.products) {
      slugs.push({ category, product: product.slug })
    }
  }
  return slugs
}
